training:
  batch_size: 256
  epochs: 50
  lr: 0.1   # {SGD: 0.1, Adam: 0.001}
  optim_name: SGD   # SGD or Adam
  model_name: eenet32   # [DNN, MNIST_CNN, CIFAR10_CNN,
                          # LeNet_5, ResNet_18, ResNet_34,
                          # B_LeNet_5, B_AlexNet, B_ResNet_18, B_ResNet_34
                          # eenet18, eenet34, eenet50, eenet101, eenet152,
                          # eenet20, eenet32, eenet44, eenet56, eenet110]
  dataset: CIFAR10   # [MNIST, CIFAR10, CIFAR100]
  num_ee: 2  # [2, 4, 8]
  distribution: pareto  # [pareto, linear, fine] # exitの分布を決定するパラメータ
  exit_type: bnpool  # [plain, bnpool]　
  loss_func: v2  # [v1, v2, v3, v4]
  zero_init_residual: True  # bool # 初期化方法の違いによる性能差を評価するためのフラグ
  exit_plot_num: 8  # 結果のプロット数
  coef_lambda: 0.5  # 損失関数の重み付けに使用するパラメータ

FL:
  global_rounds: 100
  num_clients: 10
  dirichlet: 0.1   # [0.1, 1e20]
  ite_num: 1
  cohort: 5
